backend/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
# from .views import MyLogoutView

urlpatterns = [
    path('blog_main', views.blog_main, name= 'blog_main'),
    path('create', views.create, name='create'),
    path('search', views.search, name='search'),
    path('blog_categories/<int:categ_id>/', views.blog_categories, name='blog_categories'),
    path('post/<int:post_id>/', views.post, name='post'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', views.logout_jwt, name='logout'),
    path('registration', views.registration, name='registration'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('/<int:post_id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('likes/<int:post_id>/', views.likes, name='likes'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('comment_button/<int:post_id>/', views.comment_button, name='comment_button'),
    path('my_view', views.my_view, name='my_view'),
    path('login_jwt', views.login_jwt, name='login_jwt'),
    path('get_user_by_jwt', views.get_user_by_jwt, name='get_user_by_jwt')
]

backend/grandezza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('registration', include('registration.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    # path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    # path('orders', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

backend/shop/urls.py
from django.urls import path
from . import views
# from django.contrib.auth.views import LoginView, LogoutView
# from .views import MyLogoutView
# from django.contrib import admin

urlpatterns = [
    path('', views.main, name='main'),
    path('catalog', views.catalog, name='catalog'),
    # path('catalog_category/<int:categ_id>/', views.catalog_category, name='catalog_category'),
    path('cat_category', views.cat_category, name='cat_category'),
    path('dog_category', views.dog_category, name='dog_category'),
    path('rabbit_category', views.rabbit_category, name='rabbit_category'),
    path('search', views.search_shop, name='search_shop'),
    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
    path('contact', views.contact_us, name='contact'),
    path('for_pets/<int:prod_id>', views.for_pets, name='for_pets'),
    path('product', views.product, name='product'),
    path('comments/<int:prod_id>', views.comments, name='comments'),
    path('get_product_comments/<int:prod_id>',
         views.get_product_comments, name='get_product_comments')
    # path('products', views.products, name='products'),
]

backend/shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.urls import reverse


class Gender(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Catalog(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Coat(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Breed(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Fur(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Pets(models.Model):
    PRODUCT_TYPES = (
        ('cat', 'Cat'),
        ('dog', 'Dog'),
        ('rabbit', 'Rabbit')
    )

    type = models.CharField(max_length=30, choices=PRODUCT_TYPES)
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=600, null=True, blank=True)
    images = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(Catalog, on_delete=models.CASCADE)
    avaible = models.BooleanField(default=True)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    fur = models.ForeignKey(Fur, on_delete=models.CASCADE,
                            null=True, blank=True, related_name='fur_set')
    color = models.ForeignKey(
        Color, on_delete=models.CASCADE, null=True, blank=True, related_name='color_set')
    coat = models.ForeignKey(
        Coat, on_delete=models.CASCADE, null=True, blank=True, related_name='coat_set')
    breed = models.ForeignKey(
        Breed, on_delete=models.CASCADE, null=True, blank=True, related_name='breed_set')
    size = models.ForeignKey(
        Size, on_delete=models.CASCADE, null=True, blank=True, related_name='size_set')

    def __str__(self):
        return f"{self.name} ({self.type})"

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"id": self.id})


class ContactUs(models.Model):
    first_name = models.CharField(max_length=40)
    email = models.EmailField()
    message = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name}, {self.email}"


class PetProd(models.Model):
    category = models.ForeignKey(Catalog, on_delete=models.CASCADE)
    name = models.CharField(max_length=600)
    avaible = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=900)
    image = models.ImageField(upload_to='pet_prod')

    def avarage_rating(self):
        total_ratings = self.ratings.aggregate(models.Avg('rating'))
        return total_ratings['rating__avg'] or 0

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        PetProd, on_delete=models.CASCADE, related_name='ratings')
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')


class ProdComment(models.Model):
    text = models.CharField(max_length=800)
    product = models.ForeignKey(PetProd, on_delete=models.CASCADE)
    published_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.user.id}: {self.text}'

backend/shop/forms.py
from django import forms
from shop.models import ContactUs, ProductReview, ProdComment


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['first_name', 'email', 'message',]


class RatingForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['rating',]
        widgets = {
            'rating': forms.RadioSelect(choices=[(i, f"{i} Stars") for i in range(1, 6)]),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = ProdComment
        fields = ['text',]

backend/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.utils.timezone import now
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
import jwt
from django.conf import settings
import logging

logger = logging.getLogger(__name__)

from blog.views import get_user_by_jwt, decode_jwt
from .models import Catalog, Pets, Breed, Coat, Size, Color, Fur, Gender, ContactUs, PetProd, ProductReview, ProdComment
from shop.forms import ContactUsForm, RatingForm, CommentForm


from django.db.models import Q


def main(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            form_check = {
                'first_name': form.cleaned_data.get('first_name', ''),
                'email': form.cleaned_data.get('email', ''),
                'message': form.cleaned_data.get('message', ''),
            }
            form_data = {
                'is_valid': True,
                'errors': None,
                'cleaned_data': form_check
            }
            return JsonResponse(form_data)
        else:
            errors = {
                'form_check_error': form.errors.as_json()
            }
            return JsonResponse(errors)

    return JsonResponse({'error': 'Invalid request method'}, status=405)


def catalog(request):
    pets = Pets.objects.all()
    categories = Catalog.objects.all()
    products = PetProd.objects.all()

    context = {
        'pets': list(pets.values()),
        'categories': list(categories.values()),
        'products': list(products.values()),
    }

    return JsonResponse(context)


def cat_category(request):
    categories = Catalog.objects.all()
    pets = Pets.objects.filter(type='cat')
    genders = Gender.objects.all()

    cat_coats = Coat.objects.all()
    cat_breeds = Breed.objects.all()

    cat_gender = request.GET.getlist('cat-gender')
    cat_coat = request.GET.getlist('cat-coat')
    cat_breed = request.GET.getlist('cat-breed')

    filter_criteria = Q()

    if cat_gender:
        filter_criteria &= Q(gender__name__in=cat_gender)
    if cat_coat:
        filter_criteria &= Q(coat__name__in=cat_coat)
    if cat_breed:
        filter_criteria &= Q(breed__name__in=cat_breed)

    if filter_criteria:
        pets = pets.filter(filter_criteria)

    categ_serial = list(categories.values())
    pets_serial = list(pets.values())
    genders_serial = list(genders.values())

    cat_coats_serail = list(cat_coats.values())
    cat_breeds_serial = list(cat_breeds.values())

    context = {
        'categories': categ_serial,
        'cats': pets_serial,
        'genders': genders_serial,
        'selected_genders': cat_gender,
        'selected_coats': cat_coat,
        'selected_breeds': cat_breed,
        'cat_coats': cat_coats_serail,
        'cat_breeds': cat_breeds_serial,
    }

    return JsonResponse(context)


def dog_category(request):
    categories = Catalog.objects.all()
    pets = Pets.objects.filter(type='dog')
    genders = Gender.objects.all()

    dog_sizes = Size.objects.all()
    dog_breeds = Breed.objects.all()
    dog_coats = Coat.objects.all()

    dog_size = request.GET.getlist('dog-size')
    dog_coat = request.GET.getlist('dog-coat')
    dog_breed = request.GET.getlist('dog-breed')
    dog_gender = request.GET.getlist('dog-gender')

    filter_criteria = Q()

    if dog_gender:
        filter_criteria &= Q(gender__name__in=dog_gender)
    if dog_size:
        filter_criteria &= Q(size__name__in=dog_size)
    if dog_breed:
        filter_criteria &= Q(breed__name__in=dog_breed)
    if dog_coat:
        filter_criteria &= Q(coat__name__in=dog_coat)

    if filter_criteria:
        pets = pets.filter(filter_criteria)

    category_serial = list(categories.values())
    pets_serial = list(pets.values())
    genders_serial = list(genders.values())

    dog_sizes_serail = list(dog_sizes.values())
    dog_coats_serial = list(dog_coats.values())
    dog_breeds_serial = list(dog_breeds.values())

    context = {
        'categories': category_serial,
        'dogs': pets_serial,
        'genders': genders_serial,
        'dog_coats': dog_coats_serial,
        'dog_breeds': dog_breeds_serial,
        'dog_sizes': dog_sizes_serail,
        'selected_coat': dog_coat,
        'selected_breed': dog_breed,
        'selected_gender': dog_gender,
        'selected_size': dog_size,
    }

    return JsonResponse(context)


def rabbit_category(request):
    categories = Catalog.objects.all()
    pets = Pets.objects.filter(type='rabbit')
    genders = Gender.objects.all()

    rabbit_furs = Fur.objects.all()
    rabbit_colors = Color.objects.all()

    rabbit_gender = request.GET.getlist('rabbit-gender')
    rabbit_fur = request.GET.getlist('rabbit-fur')
    rabbit_color = request.GET.getlist('rabbit-color')

    filter_criteria = Q()

    if rabbit_gender:
        filter_criteria &= Q(gender__name__in=rabbit_gender)
    if rabbit_fur:
        filter_criteria &= Q(fur__name__in=rabbit_fur)
    if rabbit_color:
        filter_criteria &= Q(color__name__in=rabbit_color)

    if filter_criteria:
        pets = pets.filter(filter_criteria)

    categories_serial = list(categories.values())
    pets_serial = list(pets.values())
    genders_serial = list(genders.values())

    rabbit_furs_serial = list(rabbit_furs.values())
    rabbit_colors_serial = list(rabbit_furs.values())

    context = {
        'rabbits': pets_serial,
        'categories': categories_serial,
        'rabbit_colors': rabbit_colors_serial,
        'genders': genders_serial,
        'rabbit_furs': rabbit_furs_serial,
        'selected_gender': rabbit_gender,
        'selected_fur': rabbit_fur,
        'selected_color': rabbit_color,
    }

    return JsonResponse(context)


def product(request):
    products = PetProd.objects.all()
    product_type = 'petprod'

    prod_serial = list(products.values())

    context = {
        'prods': prod_serial,
        'product_type': product_type,
    }

    return JsonResponse(context)


def for_pets(request, prod_id):
    product = get_object_or_404(PetProd, id=prod_id)
    user_rating = None
    product_type = 'petprod'
    form_data = {}

    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            review, created = ProductReview.objects.update_or_create(
                user=request.user,
                product=product,
                defaults={'rating': form.cleaned_data['rating']}
            )
            user_rating = review.rating
            form_data = {
                'rating': review.rating
            }

    else:
        form = RatingForm()

    user_review = ProductReview.objects.filter(
        user=request.user, product=product).first()
    if user_rating:
        user_rating = user_review.rating

    reviews = ProductReview.objects.filter(product=product)

    product_serial = {
        'id': product.id,
        'category': product.category.name,
        'name': product.name,
        'avaible': product.avaible,
        'stock': product.stock,
        'price': product.price,
        'description': product.description,
        'image': product.image.url
    }

    reviews_serial = list(reviews.values())

    context = {
        'form': form_data,
        'product': product_serial,
        'user_rating': user_rating,
        'avarage_rating': product.avarage_rating(),
        'product_type': product_type,
        'reviews': reviews_serial,
    }

    return JsonResponse(context)


def product_detail(request, id):
    pets = Pets.objects.filter(id=id, avaible=True).first()
    product_type = 'pets'

    if not pets:
        print('nothing')

    pets_serial = {
        'id': pets.id,
        'name': pets.name,
        'price': pets.price,
        'description': pets.description,
        'images': pets.images.url,
        'category': pets.category.name,
        'avaible': pets.avaible,
        'gender': pets.gender.name,
        'fur': pets.fur.name if pets.fur else None,
        'color': pets.color.name if pets.color else None,
        'breed': pets.breed.name if pets.breed else None,
        'coat': pets.coat.name if pets.coat else None,
        'size': pets.size.name if pets.size else None
    }

    context = {
        'product': pets_serial,
        'product_type': product_type,
    }

    return JsonResponse(context)


def search_shop(request):
    query = request.GET.get('query', '')

    pets = Pets.objects.filter(Q(name__icontains=query))

    pets_serial = list(pets.values())

    context = {
        'pets': pets_serial,
    }

    return JsonResponse(context)


def contact_us(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            form_check = {
                'first_name': form.cleaned_data.get('first_name', ''),
                'email': form.cleaned_data.get('email', ''),
                'message': form.cleaned_data.get('message', ''),
            }
            form_data = {
                'is_valid': True,
                'errors': None,
                'cleaned_data': form_check
            }
            return JsonResponse(form_data)
        else:
            errors = {
                'form_check_error': form.errors.as_json()
            }
            return JsonResponse(errors)

    return JsonResponse({'error': 'Invalid request method'}, status=405)

@csrf_exempt
def comments(request, prod_id):

backend/templates/shop/cat_category.html
{% extends "shop/baseCategory.html" %}

{% block content %}
<div class="flex-container">

    <aside class="aside">
        <div class="box-category">
    
            <div class="category">
                <a href="{% url 'catalog' %}" class="categories-a"> Categories </a>
                <form action="{% url 'cat_category'%}" method="GET">
                    <ul>
                        <li>
                            <div class="filter cat-filter">
                                <h4>Cat Filters</h4>
                                <div class="check-boxes">
                                    <h1 class="h1-filter"> Filter by gender</h1>
                                    {% for gender in genders %}
                                    <label>
                                        <input type="checkbox" name="cat-gender" value="{{ gender.name }}" {% if gender.name in selected_genders %}checked{% endif %}>
                                        {{ gender.name }}
                                    </label>
                                    {% endfor %}
                                </div>
    
                                <div class="check-boxes">
                                    <h1 class="h1-filter"> Filter by coat</h1>
                                    {% for coat in cat_coats %}
                                    <label>
                                        <input type="checkbox" name="cat-coat" value="{{ coat.name }}" {% if coat.name in selected_coats %}checked{% endif %}>
                                        {{ coat.name }}
                                    </label>
                                    {% endfor %}
                                </div>
    
                                <div class="check-boxes">
                                    <h1 class="h1-filter"> Filter by breed</h1>
                                    {% for breed in cat_breeds %}
                                    <label>
                                        <input type="checkbox" name="cat-breed" value="{{ breed.name }}" {% if breed.name in selected_breeds %}checked{% endif %}>
                                        {{ breed.name }}
                                    </label>
                                    {% endfor %}
                                </div>
                            </div>
                        </li>
                    </ul>
                    <button type="submit" class="custom-button">Apply Filters</button>
                </form>
                <h1 class="h1-filter-price">Price Range:</label>
                <div class="filter-group">
                    <h1 class="h1-filter-group">From</h1>
                    <input type="number" id="price-number" name="price-number" min="0" max="5000" step="50">
                    <h1 class="h1-filter-group">To</h1>
                    <input type="number" id="price-number" name="price-number" min="0" max="5000" step="50">
                </div>
            </div>
        </div>
    
    </aside>
    
    {% comment %} <div class="container">
        <div class="row">
            {% for cat in cats %}
            <div class="col-md-4 mb-4"> <!-- Adjust column width based on your layout -->
                <div class="card">
                    <img src="{{ cat.images.url }}" class="card-img-top" alt="{{ cat.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ cat.name }}</h5>
                        <p class="card-text">Price: {{ cat.price }}</p>
                        <p class="card-text">Category: {{ cat.category }}</p>
                        <a href="{% url 'product_detail' cat.id %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div> {% endcomment %}

<div class="custom-container">
    <div class="custom-row">
        {% for cat in cats %}
        <div class="custom-col">
            <div class="custom-product-card">
                <img src="{{ cat.images.url }}" class="custom-product-image" alt="{{ cat.name }}">
                <div class="custom-product-body">
                    <h5 class="custom-product-title">{{ cat.name }}</h5>
                    <p class="custom-product-price">Price: ${{ cat.price }}</p>
                    <p class="custom-product-category">Category: {{ cat.category }}</p>
                    <a href="{% url 'product_detail' cat.id %}" class="custom-button">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% comment %} <div class="products">
    {% for cat in cats %}
    <div class="show-prod">
        <div class="prod-info">
            <img src="{{ cat.images.url }}" alt="{{ cat.name }}" class="prod-img">
            <a href="{% url 'product_detail' cat.id %}"> {{cat.name}} </a>
            <h1> {{ cat.name }}</h1>
            <p> {{ cat.price }} </p>
            <p> {{ cat.category }} </p>
        </div>
    </div>
    {% endfor %}
</div> {% endcomment %}

{% endblock content %}

backend/templates/shop/main.html
{% extends "shop/base.html" %}

{% block content %}

{% load static %}

<main class="main">
    <section class="about-section">
        <h5 class="about-company">
            About company
        </h5>
        <div class="first-about">
            <div class="about-us-div">
                <div class="img-about">
                    <img class="img" src="{% static 'shop/images/mom.jpg' %}" alt="smth went wrong">
                </div>
                <div class="text-about">
                    <h4 class="discription">
                        About us
                    </h4>
                    <div class="box-about">
                        <em>
                            ``Looking for a British and Scottish kitten?
                            Then you are on the right way.

                            We have been breeding British and Scottish cats since 2017.

                            Owner of the cattery is Klimenko Lyubov.

                            The cattery is registered in the APFC club on 10.11.2017, 
                            registration number WCF-UA-0120 and is part of the DRPFC "Alisa".
                            The catteryname within the World Cat Federation (WCF) doesn’t transferable, 
                            and it is protected. Specialization of the cattery - breeding of British and 
                            Scottish cats, colors Ny11, ny1133, ns12, ns1233, ns11, ns1133, ny25, ay11, 
                            ay12. We select producers not only according to the standard of development 
                            and health, but also according to their character. Our cats love affection 
                            and attention, but at the same time they do not exclude their pedigree 
                            feature - the British and Scots are not intrusive animals.
                            Kittens of our breeding are traced in Europe, Asia, America, Australia 
                            and Japan.``
                        </em>
                    </div>
                </div>

            </div>

    </section>
    {% comment %} <div id="carousel" class="carousel">
        <button class="arrow prev"> <- </button>
        <div class="gallery">
            <ul>
                <li>
                    <img src="{% static 'shop/images/slides/cat1.jfif' %}" alt="smth went wrong">
                </li>
                <li>
                <img src="../images/slides/cat2.png" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat3.jpg" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat4.jfif" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat4.jfif" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat4.jfif" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat4.jfif" alt="smth went wrong">
                </li>
                <li>
                    <img src="../images/slides/cat4.jfif" alt="smth went wrong">
                </li>
            </ul>
        </div>
        <button class="arrow next"> -> </button>
    </div> {% endcomment %}
    {% comment %} <div class="contact-container-form">
        <form action="{% url 'contact_us' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button> 
        </form>
    </div> {% endcomment %}
</main>
<section class="contact-section section-padding" id="section_5">
    <div class="container">
        <div class="row">   

            <div class="col-lg-12 col-12">
                <em class="text-white">Say Hello</em>
                <h2 class="text-white mb-4 pb-lg-2">Contact</h2>
            </div>

            <div class="col-lg-6 col-12">
                <form action="{% url 'contact_us' %}" method="POST" class="custom-form contact-form" role="form">
                    {% csrf_token %}
                <div class="row">
                    
                    <div class="col-lg-6 col-12">
                        <label for="id_first_name" class="form-label"> {{ form.first_name.label }} <sup class="text-danger">*</sup></label>
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            <div class="text-danger">{{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-lg-6 col-12">
                        <label for="id_email" class="form-label"> {{ form.email.label }} </label>
                        {{ form.email }}

                        {% comment %} <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Jack@gmail.com" required=""> {% endcomment %}
                    </div>

                    <div class="col-12">
                        <label for="id_message" class="form-label">How can we help?</label>
                        <div class="form-contact">
                            {{ form.message }}
                        </div>

                        {% comment %} <textarea name="message" rows="4" class="form-control" id="message" placeholder="Message" required=""></textarea> {% endcomment %}
                        
                    </div>
                </div>

                <div class="col-lg-5 col-12 mx-auto mt-3">
                    <button type="submit" class="form-control">Send Message</button>
                </div>
                
            </form>
            </div>
        </div>
    </div>
</section>





{% comment %} <section class="contact-section section-padding" id="section_5">
    <div class="container">
        <div class="row">   

            <div class="col-lg-12 col-12">
                <em class="text-white">Say Hello</em>
                <h2 class="text-white mb-4 pb-lg-2">Contact</h2>
            </div>

            <div class="col-lg-6 col-12">
                <form action="#" method="post" class="custom-form contact-form" role="form">

                <div class="row">
                    
                    <div class="col-lg-6 col-12">
                        <label for="name" class="form-label">Name <sup class="text-danger">*</sup></label>

                        <input type="submit" name="name" id="name" class="form-control" placeholder="Jackson" required="">
                    </div>

                    <div class="col-lg-6 col-12">
                        <label for="email" class="form-label">Email Address</label>

                        <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Jack@gmail.com" required="">
                    </div>

                    <div class="col-12">
                        <label for="message" class="form-label">How can we help?</label>

                        <textarea name="message" rows="4" class="form-control" id="message" placeholder="Message" required=""></textarea>
                        
                    </div>
                </div>

                <div class="col-lg-5 col-12 mx-auto mt-3">
                    <button type="submit" class="form-control">Send Message</button>
                </div>
                
            </form>
            </div>
        </div>
    </div>
</section> {% endcomment %}

{% endblock content %}