backend/blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
# from .views import MyLogoutView

urlpatterns = [
    path('blog_main', views.blog_main, name= 'blog_main'),
    path('create', views.create, name='create'),
    path('search', views.search, name='search'),
    path('blog_categories/<int:categ_id>/', views.blog_categories, name='blog_categories'),
    path('post/<int:post_id>/', views.post, name='post'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', views.logout_jwt, name='logout'),
    path('registration', views.registration, name='registration'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('/<int:post_id>/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('likes/<int:post_id>/', views.likes, name='likes'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('comment_button/<int:post_id>/', views.comment_button, name='comment_button'),
    path('my_view', views.my_view, name='my_view'),
    path('login_jwt', views.login_jwt, name='login_jwt'),
    path('get_user_by_jwt', views.get_user_by_jwt, name='get_user_by_jwt')
]

backend/grandezza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('registration', include('registration.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    # path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    # path('orders', include(('orders.urls', 'orders'), namespace='orders')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

backend/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    likes = models.ManyToManyField(User, related_name='likes')
    
    def __str__(self):
        return f"{self.title}: {self.category}"
    
class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images', null=True, blank=True)
    
    def __str__(self):
        return f"{self.post} - {self.image}"
    
class Comments(models.Model):
    text = models.TextField(max_length=600)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    published_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.text}"
    
    
class Country(models.Model):
    name = models.CharField(max_length=60)
    
    def __str__(self):
        return self.name
    
class City(models.Model):
    name = models.CharField(max_length=80)
    country = models.OneToOneField(Country, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=25)
    avatar = models.ImageField(upload_to='user_avatars', null=True, blank=True, default='user_avatars/default-avatar.webp')
    country = models.ManyToManyField(Country)
    city = models.ManyToManyField(City)
    background_pic = models.ImageField(upload_to='background_pic', null=True, blank=True, default='background_pic/profile-picture-background-1uip4ytll6lbmfp5.jpg')
    
    def __str__(self):
        return self.user.username
    
class Adress(models.Model):
    street = models.CharField(max_length=300)
    private_house_number = models.IntegerField(null=True, blank=True)
    entrance_number = models.CharField(max_length=40, null=True, blank=True)
    flat_num = models.IntegerField(null=True, blank=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.street}, {self.private_house_number}, {self.entrance_number}, {self.flat_num}"

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('post', 'user')

backend/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.db.models import Count
from django.utils.timezone import now
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.views import View
from django.core.paginator import Paginator
from django import template
from django.core.mail import send_mail
from django.conf import settings
import jwt
from datetime import datetime, timedelta
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
import logging

logger = logging.getLogger(__name__)
from django.contrib.auth import get_user_model


from blog.models import Category, Post, Tag, Comments, Adress, PostImage, Profile
from blog.forms import PostForm, PostImageForm, ImageFormSet, CommentsForm, AvatarForm, UserRegister, UserUpdateForm, AdressForm, AdressFormSet, LoginForm, JwtForm


def blog_main(request):
    posts = Post.objects.all().order_by('-published_date')
    tags = Tag.objects.all()
    categories = Category.objects.all()
    user = request.user

    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post = Post.objects.get(id=post_id)
        if post.likes.filter(id=user.id).exists():
            post.likes.remove(user)
        else:
            post.likes.add(user)

    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    liked_post_ids = []
    if user.is_authenticated:
        liked_post_ids = list(user.likes.values_list('id', flat=True))

    context = {
        'page_obj': list(page_obj.object_list.values()),
        'tags': list(tags.values()),
        'categories': list(categories.values()),
        'liked_post_ids': liked_post_ids,
    }

    return JsonResponse(context)


def search(request):
    query = request.GET.get('query-search', '')

    post = Post.objects.filter(
        Q(title__icontains=query) | Q(user__username__icontains=query))

    context = {
        'post': list(post.values()),
    }

    return JsonResponse(context)


def blog_categories(request, categ_id=None):
    category_obj = get_object_or_404(Category, pk=categ_id)

    posts = Post.objects.filter(
        category=category_obj).order_by('-published_date')
    number_of_posts = Post.objects.filter(category=category_obj).count()

    paginator = Paginator(posts, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'posts': list(posts.values()),
        'number_of_posts': number_of_posts,
        'page_obj': list(page_obj.object_list.values()),
    }

    return JsonResponse(context)


def post(request, post_id=None):
    post = get_object_or_404(Post, id=post_id)
    comments = Comments.objects.filter(post=post).order_by('-published_date')
    user = request.user
    user_has_liked = post.likes.filter(id=user.id).exists()

    if request.method == 'POST':
        comments_form = CommentsForm(request.POST)
        if comments_form.is_valid():
            comment = comments_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.published_date = now()
            comment.save()

            user_data = {
                'username': user.username
            }

            comments_cd = {
                'id': comment.id,
                'text': comment.text,
                'published_date': comment.published_date.isoformat(),
                'user': user_data
            }

            form_data = {
                'is_valid': True,
                'errors': None,
                'cleaned_data': comments_cd
            }

            return JsonResponse(form_data)
        if user_has_liked:
            post.likes.remove(user)
            user_has_liked = False
        else:
            post.likes.add(user)

    context = {
        'post': {
            'id': post.id,
            'title': post.title,
            'content': post.content,
            'published_date': post.published_date,
            'likes_count': post.likes.count()
        },
        'comments': list(comments.values()),
        'user_has_liked': user_has_liked,
    }

    return JsonResponse(context)


@login_required
def likes(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    user_has_liked = post.likes.filter(id=user.id).exists()
    print(f"Debug: user_has_liked={user_has_liked}")

    if request.method == 'POST':
        if user_has_liked:
            post.likes.remove(user)
            user_has_liked = False
            print(f"Debug: User unliked post. user_has_liked={user_has_liked}")
        else:
            post.likes.add(user)
            user_has_liked = True
            print(f"Debug: User liked post. user_has_liked={user_has_liked}")

    post_user = {
        'id': post.user.id,
        'username': post.user.username,
        'email': post.user.email
    }

    context = {
        'post': {
            'id': post.id,
            'title': post.title,
            'content': post.content,
            'published_date': post.published_date,
            'likes_count': post.likes.count(),
            'user': post_user
        },
        'user_has_liked': user_has_liked,
    }

    return JsonResponse(context)


def comment_button(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        user_data = {
            'id': request.user.id,
            'username': request.user.username
        }

        category_data = {
            'id': post.category.id,
            'name': post.category.name
        } if post.category else None

        image_urls = []

        post_cd = {
            'id': post.id,
            'title': post.title,
            'content': post.content,
            'published_date': post.published_date.isoformat(),
            'user': user_data,
            'category': category_data
        }

        form_data = {
            'post_form': {
                'is_valid': True,
                'errors': None,
                'cleaned_data': post_cd
            },
            'image_form': {
                'is_valid': True,
                'errors': None,
                'cleaned_data': image_urls
            }
        }

        user_data = {
            'id': request.user.id,
            'username': request.user.username
        }

        category_data = {
            'id': post.category.id,
            'name': post.category.name
        } if post.category else None

        image_urls = []

        post_cd = {
            'id': post.id,
            'title': post.title,
            'content': post.content,
            'published_date': post.published_date.isoformat(),
            'user': user_data,
            'category': category_data
        }

        form_data = {
            'post_form': {
                'is_valid': True,
                'errors': None,
                'cleaned_data': post_cd
            },
            'image_form': {
                'is_valid': True,
                'errors': None,
                'cleaned_data': image_urls
            }
        }

    return JsonResponse(form_data)


def comment_delete(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comments = get_object_or_404(Comments, id=comment_id)

    if request.method == "POST":
        if request.user.is_authenticated and request.user == comments.user:
            if request.user == comments.user:
                comments.delete()
                return JsonResponse({'success': True, 'message': 'Comment deleted successfully'})

        return JsonResponse({
            'success': False,
            'message': 'Comment not deleted successfully'
        })


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        image_form = ImageFormSet(
            request.POST, request.FILES, queryset=PostImage.objects.none())
        if form.is_valid() and image_form.is_valid():
            post = form.save(commit=False)
            post.published_date = now()
            post.user = request.user
            post.save()

            user_data = {
                'id': request.user.id,
                'username': request.user.username
            }

            category_data = {
                'id': post.category.id,
                'name': post.category.name
            } if post.category else None

            image_urls = []

            post_cd = {
                'id': post.id,
                'title': post.title,
                'content': post.content,
                'published_date': post.published_date.isoformat(),
                'user': user_data,
                'category': category_data
            }

            form_data = {
                'post_form': {
                    'is_valid': True,
                    'errors': None,
                    'cleaned_data': post_cd
                },
                'image_form': {
                    'is_valid': True,
                    'errors': None,
                    'cleaned_data': image_urls
                }
            }

            for form in image_form.cleaned_data:
                if form:
                    image = form['image']
                    post_image = PostImage.objects.create(
                        post=post, image=image)

backend/templates/blog/blog.html
{% extends "blog/base_blog.html" %}

{% block content %}
{% load static %}
            <form action="{% url 'create' %}" method='POST'>
                <div class="box-create-post">
                    <textarea name="text" class="form-control" rows="10">
                        Create post
                    </textarea>
                    <a href="{{ image.form }}">
                        <img src="#" alt="#">
                    </a>
                    {% comment %} <input type="text" placeholder="Create your post here"> {% endcomment %}
                    <button type="submit"> Publish </button>
                </div>
            </form>
            <div class="post-box">
                {% for post in page_obj %}
                <div class="post-row">
                    <div class="post-info">
                        <div class="user-thumbnail">
                            <img src="{{ post.user.profile.avatar.url }}" alt="Avatar">
                        </div>
                        <div class="user-details">
                            <p class="username">{{ post.user.username }}</p>
                            <p class="name">@{{ post.user }}</p>
                            <p class="published-date">{{ post.published_date }}</p>
                        </div>
                    </div>
                    <h1 class="post-title">
                        <a href="{% url 'post' post.id %}">{{ post.title }}</a>
                    </h1>
                    <p class="post-content">{{ post.content }}</p>
                    {% for image in post.postimage_set.all %}
                    <div class="box-post-img">

                        <img class="post-img" src="{{ image.image.url }}" alt="">
                    </div>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <div class="likes-box">
                        <form method="POST" action="{% url 'likes' post.id %}">
                            {% csrf_token %}
                            <div class="likes-container">
                                <div class="likes-icon-container">
                                    {% if post.id in liked_post_ids %}
                                    
                                    <button type="submit" class="btn-like">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-through-heart-fill" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.854 15.854A.5.5 0 0 1 2 15.5V14H.5a.5.5 0 0 1-.354-.854l1.5-1.5A.5.5 0 0 1 2 11.5h1.793l3.103-3.104a.5.5 0 1 1 .708.708L4.5 12.207V14a.5.5 0 0 1-.146.354zM16 3.5a.5.5 0 0 1-.854.354L14 2.707l-1.006 1.006c.236.248.44.531.6.845.562 1.096.585 2.517-.213 4.092-.793 1.563-2.395 3.288-5.105 5.08L8 13.912l-.276-.182A24 24 0 0 1 5.8 12.323L8.31 9.81a1.5 1.5 0 0 0-2.122-2.122L3.657 10.22a9 9 0 0 1-1.039-1.57c-.798-1.576-.775-2.997-.213-4.093C3.426 2.565 6.18 1.809 8 3.233c1.25-.98 2.944-.928 4.212-.152L13.292 2 12.147.854A.5.5 0 0 1 12.5 0h3a.5.5 0 0 1 .5.5z"/>
                                        </svg>
                                    </button>

                                    {% else %}
                                    
                                    <button type="submit" class="btn-like">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-through-heart" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.854 15.854A.5.5 0 0 1 2 15.5V14H.5a.5.5 0 0 1-.354-.854l1.5-1.5A.5.5 0 0 1 2 11.5h1.793l.53-.53c-.771-.802-1.328-1.58-1.704-2.32-.798-1.575-.775-2.996-.213-4.092C3.426 2.565 6.18 1.809 8 3.233c1.25-.98 2.944-.928 4.212-.152L13.292 2 12.147.854A.5.5 0 0 1 12.5 0h3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.854.354L14 2.707l-1.006 1.006c.236.248.44.531.6.845.562 1.096.585 2.517-.213 4.092-.793 1.563-2.395 3.288-5.105 5.08L8 13.912l-.276-.182a22 22 0 0 1-2.685-2.062l-.539.54V14a.5.5 0 0 1-.146.354zm2.893-4.894A20.4 20.4 0 0 0 8 12.71c2.456-1.666 3.827-3.207 4.489-4.512.679-1.34.607-2.42.215-3.185-.817-1.595-3.087-2.054-4.346-.761L8 4.62l-.358-.368c-1.259-1.293-3.53-.834-4.346.761-.392.766-.464 1.845.215 3.185.323.636.815 1.33 1.519 2.065l1.866-1.867a.5.5 0 1 1 .708.708z"/>
                                        </svg>
                                    </button>
                                    
                                    {% endif %}
                                    <p class="post-likes-p"> {{ post.likes.count }} </p>

                                </div>
                            </div>
                        </form>
                        <form action="{% url 'comment_button' post.id %}" method='POST'>
                            {% csrf_token %}
                            <button type="submit" class="btn-like">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                                    <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                                  </svg>
                            </button>
                        </form>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </span>
                    </li>
                    {% endif %}

                    {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_num }}">
                            {{ page_num }} 
                            {% if page_num == page_obj.number %}
                            <span class="visually-hidden">(current)</span>
                            {% endif %}
                        </a>
                    </li>
                    {% endfor %}
            
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </span>
                    </li>
                    {% endif %}
                </ul>
            </nav>

        {% comment %} <div class="paginator">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">
                        &laquo; first 
                    </a>
                    <a href="?page={{ page_obj.previous_page_number }}">
                        previous
                    </a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page= {{ page_obj.next_page_number }}">
                        next
                    </a>
                    <a href="?page={{ page_obj.paginator.num_pages}}"> last &raquo;</a>
                {% endif %}
            </span>
        </div> {% endcomment %}

{% endblock content %}

backend/templates/blog/create.html
{% extends "blog/base_blog.html" %}

{% block content %}

<form action="{% url 'create' %}" method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_p }}
    {{ image_form.as_p }}
    <button type="submit"> Publish </button>
</form>

{% endblock content %}




backend/templates/blog/post.html
{% extends "blog/base_blog.html" %}

{% block content %}
<div class="post-box">

    <div class="post-row">
        <div class="post-info">
            <div class="user-thumbnail">
                <img src="{{ post.user.profile.avatar.url }}" alt="Avatar">
            </div>
            <div class="user-details">
                <p class="username">{{ post.user.username }}</p>
                <p class="name">@{{ post.user }}</p>
                <p class="published-date">{{ post.published_date }}</p>
            </div>
        </div>
        <h1 class="post-title">
            <a href="{% url 'post' post.id %}">{{ post.title }}</a>
        </h1>
        <p class="post-content">{{ post.content }}</p>
        {% for image in post.postimage_set.all %}
        <img class="post-img" src="{{ image.image.url }}" alt="">
        {% endfor %}
        
    </div>
</div>

                {% if user.is_authenticated %}
                    <div class="likes-box">
                        <form method="post" action="{% url 'likes' post.id %}">
                            {% csrf_token %}
                            <div class="likes-container">
                                <div class="likes-icon-container">
                                    {% if user_has_liked %}
                                    
                                    <button type="submit" class="btn-like">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-through-heart-fill" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.854 15.854A.5.5 0 0 1 2 15.5V14H.5a.5.5 0 0 1-.354-.854l1.5-1.5A.5.5 0 0 1 2 11.5h1.793l3.103-3.104a.5.5 0 1 1 .708.708L4.5 12.207V14a.5.5 0 0 1-.146.354zM16 3.5a.5.5 0 0 1-.854.354L14 2.707l-1.006 1.006c.236.248.44.531.6.845.562 1.096.585 2.517-.213 4.092-.793 1.563-2.395 3.288-5.105 5.08L8 13.912l-.276-.182A24 24 0 0 1 5.8 12.323L8.31 9.81a1.5 1.5 0 0 0-2.122-2.122L3.657 10.22a9 9 0 0 1-1.039-1.57c-.798-1.576-.775-2.997-.213-4.093C3.426 2.565 6.18 1.809 8 3.233c1.25-.98 2.944-.928 4.212-.152L13.292 2 12.147.854A.5.5 0 0 1 12.5 0h3a.5.5 0 0 1 .5.5z"/>
                                        </svg>
                                    </button>
                                    
                                    {% else %}
                                    
                                    <button type="submit" class="btn-like">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-through-heart" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M2.854 15.854A.5.5 0 0 1 2 15.5V14H.5a.5.5 0 0 1-.354-.854l1.5-1.5A.5.5 0 0 1 2 11.5h1.793l.53-.53c-.771-.802-1.328-1.58-1.704-2.32-.798-1.575-.775-2.996-.213-4.092C3.426 2.565 6.18 1.809 8 3.233c1.25-.98 2.944-.928 4.212-.152L13.292 2 12.147.854A.5.5 0 0 1 12.5 0h3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.854.354L14 2.707l-1.006 1.006c.236.248.44.531.6.845.562 1.096.585 2.517-.213 4.092-.793 1.563-2.395 3.288-5.105 5.08L8 13.912l-.276-.182a22 22 0 0 1-2.685-2.062l-.539.54V14a.5.5 0 0 1-.146.354zm2.893-4.894A20.4 20.4 0 0 0 8 12.71c2.456-1.666 3.827-3.207 4.489-4.512.679-1.34.607-2.42.215-3.185-.817-1.595-3.087-2.054-4.346-.761L8 4.62l-.358-.368c-1.259-1.293-3.53-.834-4.346.761-.392.766-.464 1.845.215 3.185.323.636.815 1.33 1.519 2.065l1.866-1.867a.5.5 0 1 1 .708.708z"/>
                                        </svg>
                                    </button>
                                    
                                    {% endif %}
                                    <p class="post-likes-p"> {{ post.likes.count }} </p>

                                </div>
                            </div>
                        </form>
                    </div>
                {% endif %}

{% if user.is_authenticated %}
<form action="{% url 'post' post.id %}" method="POST">
    {% csrf_token %}
    <div class="comment-box">
        <div class="avatar-container">
            <img src="{{ user.profile.avatar.url }}" alt="Avatar">
        </div>
        <textarea name="text" class="comment-textarea" rows="3" placeholder="Leave a comment..."></textarea>
        <div class="comment-actions">
            <button type="submit" class="submit-button">Publish</button>
        </div>
    </div>
</form>
{% else %}
<div class="error-message">
    <h3> You can't leave comment. </h3>
</div>
{% endif %}

{% if comments %}
   {% for comment in comments %}
        <div class="comment-item">
            <div class="comment-header">
                <div class="avatar-container">
                    <img src="{{ comment.user.profile.avatar.url }}" alt="Avatar">
                </div>
                <div class="comment-details">
                    <h4 class="comment-username">
                        {{ comment.user.username }}
                        <small class="comment-date">{{ comment.published_date }}</small>
                    </h4>
                    <p class="comment-text">{{ comment.text }}</p>
                </div>
                <form action="{% url 'comment_delete' post.id comment.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">
                        Delete
                    </button>
                </form>
            </div>
        </div>
   {% endfor %}
{% else %}
    <h1>No comments yet.</h1>
{% endif %}

{% comment %} <form action="{% url 'post' post.id %}" method="POST">
    {% csrf_token %}
    <div class="comment-container">
        <div class="avatar-container">
            <img src="{{ user.profile.avatar.url }}" alt="Avatar">
        </div>
        <textarea name="text" class="comment-textarea" rows="3" placeholder="Leave a comment..."></textarea>
        <div class="comment-submit-container">
            <button type="submit" class="submit-button">Publish</button>
        </div>
    </div>
</form>

{% if comments %}
   {% for comment in comments %}
        <div class="comment-item">
            <div class="comment-header">
                <div class="avatar-container">
                    <img src="{{ user.profile.avatar.url }}" alt="Avatar">
                </div>
                <div class="comment-details">
                    <h4 class="comment-username">
                        {{ comment.user.username }}
                        <small class="comment-date">{{ comment.published_date }}</small>
                    </h4>
                </div>
            </div>
            <p class="comment-text">{{ comment.text }}</p>
        </div>
   {% endfor %}
{% else %}
    <h1>No comments yet.</h1>
{% endif %} {% endcomment %}
            {% comment %} {% if comments %}
               {% for comment in comments %}
                    <div class="media-body">
                        <h4 class="media-heading"> {{ comment.user.username }}
                            <small>{{ comment.published_date }}</small>
                        </h4>
                        {{ comment.text }}
                    </div>
               {% endfor %}
            {% else %}
                <h1>No comments yet.</h1>
            {% endif %} {% endcomment %}

{% endblock content %}